# Generated by Django 4.1.7 on 2023-03-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preparationForAnalysis', models.TextField(verbose_name='Подготовка к анализу')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('interpretationOfResults', models.TextField(verbose_name='Интерпретация результатов')),
                ('laboratoryTest', models.CharField(max_length=500, verbose_name='Лабораторные тесты')),
                ('biomaterial', models.TextField(verbose_name='Биоматериал')),
                ('deadlineDateOfIssueOfResults', models.CharField(max_length=300, verbose_name='срок выполнения день, выдачи результатов')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='laboratory/images')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон номер')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес аптеки')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб сайт (url)')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('analyze_laboratory', models.ManyToManyField(blank=True, null=True, to='laboratory.analyze')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
        migrations.CreateModel(
            name='PriceAnalyzeToLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('analyze', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyze', to='laboratory.analyze')),
                ('laboratory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_lab', to='laboratory.lab')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.AddField(
            model_name='lab',
            name='prices',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='laboratory.priceanalyzetolaboratory'),
        ),
        migrations.AddField(
            model_name='analyze',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='laboratory.category'),
        ),
        migrations.AddField(
            model_name='analyze',
            name='labs',
            field=models.ManyToManyField(blank=True, related_name='labs', to='laboratory.lab'),
        ),
        migrations.AddField(
            model_name='analyze',
            name='parent_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_subcategories', to='laboratory.analyze'),
        ),
    ]
