# Generated by Django 4.1.7 on 2023-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_analyze_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='prices',
        ),
        migrations.AddField(
            model_name='lab',
            name='prices',
            field=models.ManyToManyField(blank=True, related_name='prices', to='laboratory.priceanalyzetolaboratory'),
        ),
    ]
