# Generated by Django 4.1.7 on 2023-03-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_remove_lab_prices_lab_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='labs',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='analyze_laboratory',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='prices',
        ),
    ]
