# Generated by Django 4.1.7 on 2023-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_alter_priceanalyzetolaboratory_analyze'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='image',
            field=models.ImageField(default=1, upload_to='laboratory/images'),
            preserve_default=False,
        ),
    ]
