# Generated by Django 4.1.7 on 2023-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_analyze_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес лаборатории'),
        ),
    ]
